### ISSUE TITLE
cannot get it to open - even on the test files. 

### ISSUE THREAD

**Issue by kimusan** [bennypowers/nvim-regexplainer#11]
I have just installed nvim-regexplainer but I cannot get it to actually show up. 
I use lunarvim (nvim with config from lunarvim.org) but the config etc is the usual lua way:

```lua
{ 'bennypowers/nvim-regexplainer',
    requires = {
      'nvim-lua/plenary.nvim',
      'MunifTanjim/nui.nvim',
    },
    config = function() require'regexplainer'.setup({
   -- 'narrative'
  mode = 'narrative', -- TODO: 'ascii', 'graphical'

  -- automatically show the explainer when the cursor enters a regexp
  auto = true,

  -- Whether to log debug messages
  debug = false,

  -- 'split', 'popup'
  display = 'popup',

  mappings = {
    toggle = 'gR',
    -- examples, not defaults:
    -- show = 'gS',
    -- hide = 'gH',
    show_split = 'gP',
    show_popup = 'gU',
  },

  narrative = {
    separator = '\n',
  },
  })
  end,
}
```
I can see that it is loaded (the gR, gH etc mappings are available and also the :RegexplainerShow etc) but nothing happens when I call any of them. Nothing in :messages - even when I call :RegexplainerDebug 

nvim version 0.7.0-dev

any idea?

**Comment by bennypowers** [comment]
which language are you using?
when you cursor on the regexp and invoke `:TSPlaygroundToggle`, what do you see? please send a screenshot of the editor in that state

**Comment by bennypowers** [comment]
even better, paste the file (or a repressentative repro) along with it's filename here

**Comment by kimusan** [comment]
I use the ts file from the test folder . I just forced it to say that it requires treesitter (like with nui and plenary) and then I got this error when doing gR:

![image](https://user-images.githubusercontent.com/1150049/158328964-76f229fc-86c8-4134-bef8-4f6493787328.png)

I did not have the treesitter-playground plugin installed so had to install that. with that installed I have this:

![image](https://user-images.githubusercontent.com/1150049/158329900-95d80590-7102-4282-88ce-1ae95ad69010.png)

**Comment by kimusan** [comment]
Thanks. Installing the TS regex support was the missing piece (might be worth mentioning the treesitter requirements in the readme).

**Comment by sisrfeng** [comment]
Spent 2 hours (playing with tree-sitter coc and etc) and still do not know how to use

**Comment by bennypowers** [comment]
There's a minimal init in the test directory, and you also need to install the relevant tree sitter parsers, see the makefile.

If you can put together a minimal reproduction I'm happy to take a look at it

**Comment by kimusan** [comment]
For me installing the treesitter regex and query parsers + parser for the relevant language seemed to solve the problem.
:TSinstall query regex typescript

**Comment by bennypowers** [comment]
Closing as OP seems to have solved the problem
