### ISSUE TITLE
Incorrect interpretation of a negated character list `[^p]`

### ISSUE THREAD

**Issue by adamazing** [bennypowers/nvim-regexplainer#2]
Awesome idea! 
I tried a simple regex in a scratch buffer:
```
let reggie = /^p[^p]*p/
```
Regexplainer incorrectly explains it like so:
```
START
`p`
One of ^, or p (>= 0x)
`p`
```
![image](https://user-images.githubusercontent.com/2782959/157106562-8fdb0120-8935-4605-abe9-b325b09ab787.png)

The first caret is correctly explained as the "start" anchor, but the second caret is interpreted as part of the character list. 
The first caret inside square brackets actually negates the character list. 

So maybe the output of regexplainer would be:
```
START
`p`
Any character not in the list: `p` (>= 0x)
`p`
```

And for a character list with multiple characters, e.g. `/^p[^p^a]*p/`:
```
START
`p`
Any character not in the list: `p`, `^`, `a` (>= 0x)
`p`
```

This is how regex101 treats that last example: https://regex101.com/r/mGQXlb/1

**Comment by bennypowers** [comment]
Thanks for the report. I'll take a look

**Comment by bennypowers** [comment]
Give that a try and let me know. Thanks again for the interest and the report. 🙏

**Comment by adamazing** [comment]
Perfect! 🙇 Awesome turn-around time! Treesitter really is neat isn't it?

**Comment by bennypowers** [comment]
Yup
