### ISSUE TITLE
Remove nui dependency

### ISSUE THREAD

**Issue by barrett-ruth** [bennypowers/nvim-regexplainer#22]
I'd like to use this plugin but as someone averse to clutter installing nui.nvim for this single plugin just does not warrant it.

If you are ok with the addition of this feature I could make the PR myself.

**Comment by bennypowers** [comment]
that would be a huge change. i wouldn't want to miss out on improvements to nui either

I'd be more easily convinced if/when nvim core provides more ui primitives. 

What sort of plan do you have in mind?

**Comment by barrett-ruth** [comment]
Ah. If it is indeed a huge change then maybe I'll come back later to try and fix it. Either way, the plugin is awesome.

And by removing, I mean *optionally* removing - having the ability to configure whether nui or the crappier neovim builtin methods should be used.

**Comment by bennypowers** [comment]
opting in to some other ui is interesting. hopefully the codebase is modular enough for that. I'd review a pr to that effect
