### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by CharlesChiuGit** [bennypowers/nvim-regexplainer#32]
Currently I can only reproduce the examples in the readme, and failed to get the popup in other lang, like `bash` or `lua`? Is this plugin js/ts specific?

P.S. I had already install the `regex` `bash` `lua` ts parser and set them in `regexplainer`'s config

**Comment by bennypowers** [comment]
it requires treesitter
if the language has embedded regex grammar, it should work, and if not, not
i can't debug anything without more info

**Comment by CharlesChiuGit** [comment]
I did install treesitter and it's corresponded lang parsers, I guess maybe most of the lang I use doesn't have regex grammer embedded then.
Thanks for the reply tho.

**Comment by bennypowers** [comment]
You mean like this?

> You need to install regex with nvim-treesitter, as well as the grammar for whichever host language you're using. So for example if you wish to use Regexplainer with TypeScript sources, you need to do this:
> 
> :TSInstall regex typescript

**Comment by CharlesChiuGit** [comment]
> You mean like this?

Not really. I mean it would nice to let users know they have to check if their lang's ts parser has embedded regex grammar.

**Comment by CharlesChiuGit** [comment]
There's a snippets of my bash script, if your interested 
```bash
#!/usr/bin/env bash
# shellcheck disable=SC2059,SC2154
set -e
set -o pipefail

######################################################################
#                           Update Batcat                            #
######################################################################
printf "Fetch ${tty_blue}Batcat${tty_reset} latest release...\n"
remote_version=$(get_latest_release "sharkdp/bat")
# remote_version="v0.22.3"
remote_version_c=$(echo "$remote_version" | sed -E 's/v([0-9]+.[0-9]+.[0-9]+)/\1/')
```
