### ISSUE TITLE
Rexexplainer: loop exceeded 1000 at node start_tag

### ISSUE THREAD

**Issue by bennypowers** [bennypowers/nvim-regexplainer#38]
in certain HTML files, Regexplainer can try too hard to find a pattern in start_tag, end_tag, or text nodes. I don't have a minimal repro, but check rh-audio-player detailed-transcript.html demo, particularly in the cue elements

**Comment by ilan-schemoul** [comment]
I get this error for most files really. For example the example given for cpp https://en.cppreference.com/w/cpp/regex gives the same error when I try this plugin on std::regex word_regex("(\\w+)"); (cursor is in the string when I call RegexExplainer)
